
<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>

<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<div class="page-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h2><?php echo str_replace("&lt;br /&gt;", "", $_helper->categoryAttribute($_category, $_category->getName(), 'name')) ?></h2>
</div> <!--page-title-->


<div class="slider catslider">
<ul class="iwmm_slider bxslider">
    <li class="slide">
        <img class="slide_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/slider_slide1_bg.jpg', '_query' => '')); ?>" alt="40% off - health care essentials">

        <div class="slide_text">
            <h3 style="color: #902d97;">40% off</h3>
            <h4 style="color: #33a3f8;">health care essentials</h4>
            <p>Be prepared for cold, flu, allergy &amp; minor medical emergencies</p>
        </div>
    </li>
    <li class="slide">
        <img class="slide_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/slider_slide1_bg.jpg', '_query' => '')); ?>" alt="40% off - health care essentials">

        <div class="slide_text">
            <h3 style="color: #902d97;">40% off</h3>
            <h4 style="color: #33a3f8;">health care essentials</h4>
            <p>Be prepared for cold, flu, allergy &amp; minor medical emergencies</p>
        </div>
    </li>
    <li class="slide">
        <img class="slide_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/slider_slide1_bg.jpg', '_query' => '')); ?>" alt="40% off - health care essentials">

        <div class="slide_text">
            <h3 style="color: #902d97;">40% off</h3>
            <h4 style="color: #33a3f8;">health care essentials</h4>
            <p>Be prepared for cold, flu, allergy &amp; minor medical emergencies</p>
        </div>
    </li>
</ul>
</div>





<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($_imgUrl): ?>
    <?php echo $_imgHtml ?>
<?php endif; ?>

<?php if($_description=$this->getCurrentCategory()->getDescription() && 1 == 2): ?>
    <div class="category-description std">
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
    </div>
    <?php endif; ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
