<div class="home_category_banners">

	<div class="row">
		<div class="col">
			<a class="home_category_banner" href="#">
				<img class="home_category_banner_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/home_category_banner1_bg_noborder.jpg', '_query' => '')); ?>" alt="My Medicine">
				
				<div class="home_category_banner_text">
					<h3 class="home_category_banner_title">My<br />Medicine</h3>
					<span class="home_category_banner_more" style="color: #ffbc16;">see products</span>
				</div>
			</a>
		</div>
		<div class="col">
			<a class="home_category_banner" href="#">
				<img class="home_category_banner_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/home_category_banner2_bg_noborder.jpg', '_query' => '')); ?>" alt="My Health">
				
				<div class="home_category_banner_text">
					<h3 class="home_category_banner_title">My<br />Health</h3>
					<span class="home_category_banner_more" style="color: #00bb00;">see products</span>
				</div>
			</a>
		</div>
		<div class="col">
			<a class="home_category_banner" href="#">
				<img class="home_category_banner_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/home_category_banner3_bg_noborder.jpg', '_query' => '')); ?>" alt="Toiletries">
				
				<div class="home_category_banner_text">
					<h3 class="home_category_banner_title">Toiletries</h3>
					<span class="home_category_banner_more" style="color: #ffbc16;">see products</span>
				</div>
			</a>
		</div>
		<div class="col">
			<a class="home_category_banner" href="#">
				<img class="home_category_banner_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/home_category_banner4_bg_noborder.jpg', '_query' => '')); ?>" alt="Beauty&amp; Fragrance">
				
				<div class="home_category_banner_text">
					<h3 class="home_category_banner_title">Beauty<br />&amp; Fragrance</h3>
					<span class="home_category_banner_more" style="color: #902d97;">see products</span>
				</div>
			</a>
		</div>
	</div>

	<div class="row">
		<div class="col">
			<a class="home_category_banner" href="#">
				<img class="home_category_banner_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/home_category_banner5_bg_noborder.jpg', '_query' => '')); ?>" alt="Mamas &amp; baby">
				
				<div class="home_category_banner_text">
					<h3 class="home_category_banner_title">Mamas<br />&amp; baby</h3>
					<span class="home_category_banner_more" style="color: #ffbc16;">see products</span>
				</div>
			</a>
		</div>
		<div class="col">
			<a class="home_category_banner" href="#">
				<img class="home_category_banner_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/home_category_banner6_bg_noborder.jpg', '_query' => '')); ?>" alt="Travel Healthy">
				
				<div class="home_category_banner_text">
					<h3 class="home_category_banner_title">Travel<br />Healthy</h3>
					<span class="home_category_banner_more" style="color: #902d97;">see products</span>
				</div>
			</a>
		</div>
		<div class="col">
			<a class="home_category_banner" href="#">
				<img class="home_category_banner_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/home_category_banner7_bg_noborder.jpg', '_query' => '')); ?>" alt="Electrical Health">
				
				<div class="home_category_banner_text">
					<h3 class="home_category_banner_title">Electrical<br />Health</h3>
					<span class="home_category_banner_more" style="color: #ffbc16;">see products</span>
				</div>
			</a>
		</div>
		<div class="col">
			<a class="home_category_banner" href="#">
				<img class="home_category_banner_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/home_category_banner8_bg_noborder.jpg', '_query' => '')); ?>" alt="Mobility Aids">
				
				<div class="home_category_banner_text">
					<h3 class="home_category_banner_title">Mobility<br />Aids</h3>
					<span class="home_category_banner_more" style="color: #00bb00;">see products</span>
				</div>
			</a>
		</div>
	</div>

</div>