<div class="home_horizontal_banners">

	<div class="row">
		<div class="col">
			<a class="home_horizontal_banner" href="<?php echo Mage::getUrl('electronic-prescription'); ?>">
				<img class="home_horizontal_banner_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/home_underslider_banner1_bg.jpg', '_query' => '')); ?>" alt="Mamas &amp; baby">
			
				<div class="home_horizontal_banner_text">
					<h3 class="home_horizontal_banner_title" style="color: #ffbc16;">Electronic prescription service</h3>
					<span class="home_horizontal_banner_more" style="color: #33a3f8;">the way forward for nhs prescription</span>
				</div>
			</a>
		</div>
		<div class="col">
			<a class="home_horizontal_banner" href="<?php echo Mage::getUrl('nhs-prescription') ?>">
				<img class="home_horizontal_banner_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/home_underslider_banner2_bg.jpg', '_query' => '')); ?>" alt="Mamas &amp; baby">
			
				<div class="home_horizontal_banner_text">
					<h3 class="home_horizontal_banner_title" style="color: #902d97;">Community Pharmacy questionnaire</h3>
					<span class="home_horizontal_banner_more" style="color: #00bb00;">the way forward for nhs prescription</span>
				</div>
			</a>
		</div>
	</div>

</div>