
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $this->setData('column_count',3);
?>
<?php if(!$_productCollection->count()): ?>
<?php
$empty_category_block = Mage::getModel('cms/block')->load('lamby_empty_category');
 if($empty_category_block->getIsActive()){
     echo $this->getLayout()->createBlock('cms/block')->setBlockId('lamby_empty_category')->toHtml();
 } else { ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php } ?>
<?php else: ?>

<?php echo $this->getToolbarHtml() ?>
<!-- BEGIN CATEGORY PRODUCTS -->
<div class="category-products">
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>

    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
        <!-- BEGIN PRODUCT IMAGE -->
          <div class="product-image">
            <div class="amlabel-div">
              <?php echo Mage::helper('amlabel')->getLabels($_product) ?>
              <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(230,279); ?>" class="small-image" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
              </a>
            </div>
          </div> <!--product-image-->
          <!-- BEGIN PRODUCT SHOP -->
          <div class="product-shop">
            <div class="jsEqualProductName">
            <h2 class="product-name">
                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
            </h2>

            <?php echo $this->getPriceHtml($_product, true) ?>
                 <?php  if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                 <?php else: ?>
                        <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
                 <?php  endif;  ?>

            <div class="desc std">
              <p><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
              <p><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a></p>
            </div> <!--desc std-->
            </div>

            <!-- BEGIN ACTIONS -->
            <div class="actions">
            <?php if($_product->isSaleable()): ?>
                   <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajx-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
              <?php else: ?>
                   <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
              <?php endif; ?>
              <span class="add-to-links">
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="button link-wishlist" title="<?php echo $this->__('Add to wishlist');?>"><span><?php echo $this->__('Add to wishlist');?></span></a>
                <?php endif; ?>
                <?php if($_compareUrl=$this->getAddToCompareUrl($_product) && 1 == 2): ?>
                    <span class="separator">|</span><a href="<?php echo $_compareUrl ?>" class="button link-compare" title="<?php echo $this->__('Add to compare');?>"><span><?php echo $this->__('Add to compare');?></span></a>
                <?php endif; ?>
              </span> <!--add-to-links-->
            </div> <!--actions-->
          </div> <!--product-shop-->
        </li>
    <?php endforeach; ?>
    </ol>

    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>


  <ul class="products-grid">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>

        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">

            <div class="item-inner">
    <div class="product-wrapper">
      <div class="thumb-wrapper">
          <div class="amlabel-div">
              <?php echo Mage::helper('amlabel')->getLabels($_product) ?>
                 <?php echo $this->helper('lambysettings')->getLabel($_product);  ?>
                 <?php if(Mage::app()->getStore()->getConfig('lambysettings/lambysettings_quickview/enable')==1){?>
                 <a class="thumb" data-fancybox-type="ajax" onclick="callQuickView('<?php echo Mage::getUrl('lambysettings/index/view/id/'.$_product->getId());?>');"><span class="face"><img alt="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(268,325) ?>"></span><span class="face back"><img alt="<?php echo $this->htmlEscape($_product->getName()) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(268,325) ?>">
                      <span class="quick-view"><span><i>&nbsp;</i><?php echo $this->__('Quick View') ?></span></span>
                  </span></a>
                  <?php } else {  ?>
                     <a class="thumb" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><span class="face"><img alt="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(268,325) ?>"></span></a>
                  <?php } ?>
          </div>
      </div> <!--thumb-wrapper-->
      <div class="actions">
        <span class="add-to-links">
          <?php if ($this->helper('wishlist')->isAllow()) : ?>
           <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist');?>"><span><?php echo $this->__('Add to Wishlist');?></span></a>
          <?php endif; ?>
           <?php if($_compareUrl=$this->getAddToCompareUrl($_product) && 1 == 2): ?>
                    <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare');?>"><span><?php echo $this->__('Add to Compare');?></span></a>
            <?php endif; ?>


        </span> <!--add-to-links-->
      </div> <!--actions-->
    </div> <!--product-wrapper-->
    <div class="item-info">
      <div class="info-inner">
        <div class="jsEqualProductName">
         <div class="item-title">
             <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                  <?php $prod_name = $this->htmlEscape($_product->getName()) ;
                  if(strlen($prod_name) > 30) {echo substr($prod_name,0,30)."...";}else {echo $prod_name;}?>
             </a>
          </div> <!--item-title-->

          <div class="item-desc">
              <?php
                $my_product = Mage::getModel('catalog/product')->load($_product->getId());
                echo $my_product->getDescription();
              ?>
            </div>
            </div>

          <div class="item-content jsEqualBestsPrice">
            <?php  if($_product->getRatingSummary()): ?>
                        <div class="ratings"><div class="rating-box" style="background: none;"></div></div>
                 <?php else: ?>
                        <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
                 <?php  endif;  ?>
            <div class="item-price"><?php echo $this->getPriceHtml($_product, true) ?></div>
          </div> <!--item-content-->
      </div> <!--info-inner-->
      <div class="actions">
            <?php if($_product->isSaleable()): ?>
                <?php if($_product->getData('is_prescription_product') == '1' &&
                    (empty(Mage::getSingleton('core/session')->getPerscriptionCheck()) or
                        (Mage::getSingleton('core/session')->getPerscriptionCheck() == "no_pay" && empty(Mage::getSingleton('core/session')->getPrescriptionExemptionCheck()))
                    )){ ?>
                    <a href="#more_info_popup" data-url="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->__('More Info') ?>" class="button btn-cart btn-more-info"><span><?php echo $this->__('More Info') ?></span></a>
                <?php }else{ ?>
                    <button type="button"  title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
                <?php } ?>
            <?php else: ?>
              <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
        </div> <!--actions-->
    </div> <!--item-info-->
   </div> <!--item-inner-->

            </li>

        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>

        <?php endif ?>

        <?php endforeach ?>
  </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>
</div> <!--category-products-->

<!--div class="toolbar-bottom">
    <?php //echo $this->getToolbarHtml() ?>
</div-->

<?php endif; ?>

<div id="mgkquickview">
<div id="magikloading" style="display:none;text-align:center;margin-top:400px;"><img src="<?php echo $this->getSkinUrl('images/mgkloading.gif');?>" alt="loading">
</div></div>
<script type="text/javascript">
function callQuickView(qurl) {
    jQuery('#mgkquickview').show();
    jQuery('#magikloading').show();
    jQuery.get(qurl, function(data) {
      jQuery.fancybox(data);
      jQuery('#magikloading').hide();
jQuery('#mgkquickview').hide();
    });
 }
jQuery(".btn-more-info").fancybox({
    'transitionIn' : 'none',
    'transitionOut' : 'none'
});
jQuery(".btn-more-info").click(function(){
    jQuery('#url_redirect_product').val(jQuery(this).attr('data-url'));
});
</script>
<?php  if(Mage::getSingleton('core/session')->getPerscriptionCheck() !=null){ ?>
<div style="display: none;">
    <div id="more_info_popup">
        <h1>
            Order your prescription medicine onlinesss
        </h1>
        <p>
            We'll happily dispense this item from our online pharmacy if you have a prescription. Just enter the name that's on your prescription, select the option that's right for you and go through to the checkout. This way, you get the convenience of online ordering, with the confidence that comes from using one of the UK's most trusted pharmacies.
        </p>
        <form id="popup_prescriptioncheck_form" action="<?php echo Mage::getUrl('myprescription/index/prescriptioncheck') ?>" method="post">
            <input type="hidden" name="url_redirect_product" id="url_redirect_product" value="">
            <div class="box-1">
                <h2>What type of prescription do you have?</h2>
                <input type="radio" name="perscription_type" value="pay"><strong>NHS Prescription</strong><br>
                <p>I need to pay for this NHS prescription</p>
                <input type="radio" name="perscription_type" value="no_pay"><strong>NHS Prescription</strong><br>
                <p>I dont need to pay for this NHS prescription</p>
                <input type="radio" name="perscription_type" value="private"><strong>Private Prescription</strong><br>
                <p>I have a private prescription</p>
                <p>Please enter the name as it is on the prescription</p>
                <input type="text" id="name_on_prescription" name="name_on_prescription"/>
                <p class="message-valid-name" style="display: none;color: #d90000"><?php echo $this->__('Please enter a valid patient name');?></p>
            </div>
            <a href="#" id="submit_pop_up_form" class="button btn-submit"><span><?php echo $this->__('Continue Order') ?></span></a>
        </form>
        <a href="<?php echo Mage::getBaseUrl().'more-info-page-one'?>"><span>I don't know if I need to pay for my prescription</span></a>
        <br/>
        <a href="<?php echo Mage::getBaseUrl().'more-info-page-tow'?>"><span>I don't have a prescription</span></a>
    </div>
    <script type="text/javascript">
        jQuery('#submit_pop_up_form').click(function(){
            if(jQuery('#name_on_prescription').val().length <= 0){
                jQuery('#name_on_prescription').focus();
                jQuery('.message-valid-name').show();
                return false;
            }else{
                jQuery('.message-valid-name').hide();
            }
            jQuery('#magikloading').show();
            jQuery.ajax( {
                type: "POST",
                url: jQuery('#popup_prescriptioncheck_form').attr( 'action' ),
                data: jQuery('#popup_prescriptioncheck_form').serialize(),
                success: function( response ) {
                    jQuery('#magikloading').hide();
                    if(response.success){
                        window.location.href = response.url;
                    }else{
                        jQuery('#fancybox-close').click();
                    }
                }
            } );
        });
    </script>
</div>
<?php } ?>
