<div class="weekly_deals" style="background-image: url(<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/weekly_deals.jpg', '_query' => '')); ?>);">
	<img class="weekly_deals_product" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/weekly_deals_product.png', '_query' => '')); ?>" alt="Weekly Deals" />

	<div class="weekly_deals_text">
		<h3 class="weekly_deals_title">Weekly Deals</h3>
		<a class="button" href="#">find out more</a>
	</div>
</div>
