<div class="slider_with_banners">
	<div class="slider">
		<ul class="iwmm_slider bxslider">
			<li class="slide">
				<img class="slide_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/slider_slide1_bg.jpg', '_query' => '')); ?>" alt="40% off - health care essentials">
				
				<div class="slide_text">
					<h3 style="color: #902d97;">40% off</h3>
					<h4 style="color: #33a3f8;">health care essentials</h4>
					<p>Be prepared for cold, flu, allergy &amp; minor medical emergencies</p>
					<a class="button">find out more</a>
				</div>
			</li>
			<li class="slide">
				<img class="slide_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/slider_slide1_bg.jpg', '_query' => '')); ?>" alt="40% off - health care essentials">
				
				<div class="slide_text">
					<h3 style="color: #902d97;">40% off</h3>
					<h4 style="color: #33a3f8;">health care essentials</h4>
					<p>Be prepared for cold, flu, allergy &amp; minor medical emergencies</p>
					<a class="button">find out more</a>
				</div>
			</li>
			<li class="slide">
				<img class="slide_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/slider_slide1_bg.jpg', '_query' => '')); ?>" alt="40% off - health care essentials">
				
				<div class="slide_text">
					<h3 style="color: #902d97;">40% off</h3>
					<h4 style="color: #33a3f8;">health care essentials</h4>
					<p>Be prepared for cold, flu, allergy &amp; minor medical emergencies</p>
					<a class="button">find out more</a>
				</div>
			</li>
		</ul>
	</div>
	<div class="slider_banners">

		<div class="row">
			<div class="col">
				<a class="slider_banner" href="#">
					<img class="slider_banner_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/home_banner1_bg.jpg', '_query' => '')); ?>" alt="Toiletries">
				
					<div class="slider_banner_text">
						<span class="slider_banner_more" style="color: #00bb00;">No need to come out</span>
						<h3 class="slider_banner_title" style="color: #902d97;">Free nationwide <br />next day delivery</h3>
					</div>
				</a>
			</div>
		</div>

		<div class="row">
			<div class="col">
				<a class="slider_banner" href="#">
					<img class="slider_banner_bg" src="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/home_banner2_bg.jpg', '_query' => '')); ?>" alt="Toiletries">
				
					<div class="slider_banner_text">
						<h3 class="slider_banner_title" style="color: #ffbc16;">Electronic <br />prescription service</h3>
						<span class="slider_banner_more" style="color: #33a3f8;">the way forward <br />for nhs prescription</span>
					</div>
				</a>
			</div>
		</div>

	</div>
</div>
