<?php if($crumbs && is_array($crumbs)): ?>
  <div class="breadcrumbs">
    <div class="inner">
      <ul>
        <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
            <li class="<?php echo $_crumbName ?>">
            <?php if($_crumbInfo['link']): ?>
                <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo str_replace("&lt;br /&gt;", "", $this->htmlEscape($_crumbInfo['title'])) ?>"><?php echo str_replace("&lt;br /&gt;", "", $this->htmlEscape($_crumbInfo['label'])) ?></a>
            <?php elseif($_crumbInfo['last']): ?>
                <strong><?php echo str_replace("&lt;br /&gt;", "", $this->htmlEscape($_crumbInfo['label'])) ?></strong>
            <?php else: ?>
                <?php echo str_replace("&lt;br /&gt;", "", $this->htmlEscape($_crumbInfo['label'])) ?>
            <?php endif; ?>
            <?php if(!$_crumbInfo['last']): ?>
                <span>—› </span>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
      </ul>
    </div> <!--inner-->
  </div> <!--breadcrumbs-->
<?php endif; ?>
