<?php $config = Mage::getStoreConfig('lambysettings/lambysettings_appearance'); ?>

<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo str_replace("&lt;br /&gt;", "", $this->getTitle()) ?></title>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=no" />
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<meta name="google-site-verification" content="V7ZvzJZLkrR_mEXVe8KHsPpYTKhM2GY6JgPuinntVyc" />
<link href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $config['font']); ?>:200,300,400,500,600,700,800' rel='stylesheet' type='text/css'>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<script type="text/javascript">
  jQuery(window).scroll(function() {
   if (jQuery(this).scrollTop() > jQuery('header').height()){
       jQuery('nav').addClass("sticky");
       jQuery('.jsHeaderMain').addClass("sticky-margin");
   }
   else{
       jQuery('nav').removeClass("sticky");
       jQuery('.jsHeaderMain').removeClass("sticky-margin");
   }
});
</script>

<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<script type="text/javascript">
var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
var SKIN_URL = '<?php echo $this->helper('core/js')->getJsSkinUrl('') ?>';
</script>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

<link rel="apple-touch-icon" sizes="57x57" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/apple-touch-icon-57x57.png', '_query' => '')); ?>">
<link rel="apple-touch-icon" sizes="60x60" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/apple-touch-icon-60x60.png', '_query' => '')); ?>">
<link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/apple-touch-icon-72x72.png', '_query' => '')); ?>">
<link rel="apple-touch-icon" sizes="76x76" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/apple-touch-icon-76x76.png', '_query' => '')); ?>">
<link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/apple-touch-icon-114x114.png', '_query' => '')); ?>">
<link rel="apple-touch-icon" sizes="120x120" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/apple-touch-icon-120x120.png', '_query' => '')); ?>">
<link rel="apple-touch-icon" sizes="144x144" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/apple-touch-icon-144x144.png', '_query' => '')); ?>">
<link rel="apple-touch-icon" sizes="152x152" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/apple-touch-icon-152x152.png', '_query' => '')); ?>">
<link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/apple-touch-icon-180x180.png', '_query' => '')); ?>">
<link rel="icon" type="image/png" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/favicon-32x32.png', '_query' => '')); ?>" sizes="32x32">
<link rel="icon" type="image/png" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/favicon-194x194.png', '_query' => '')); ?>" sizes="194x194">
<link rel="icon" type="image/png" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/favicon-96x96.png', '_query' => '')); ?>" sizes="96x96">
<link rel="icon" type="image/png" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/android-chrome-192x192.png', '_query' => '')); ?>" sizes="192x192">
<link rel="icon" type="image/png" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/favicon-16x16.png', '_query' => '')); ?>" sizes="16x16">
<link rel="manifest" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/manifest.json', '_query' => '')); ?>">
<link rel="shortcut icon" href="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/favicon.ico', '_query' => '')); ?>">
<meta name="msapplication-TileColor" content="#00aba9">
<meta name="msapplication-TileImage" content="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/mstile-144x144.png', '_query' => '')); ?>">
<meta name="msapplication-config" content="<?php echo $this->getUrl('', array('_direct' => 'skin/frontend/rwd/lamby/images/iwmm/icons/browserconfig.xml', '_query' => '')); ?>">
<meta name="theme-color" content="#ffffff">
